# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/coe_user/Documents/ECE574_Local/homework/hw3/assignment3.srcs/sources_1/ip/dsp_addsub_piped_2/dsp_addsub_piped_2.xci
# IP: The module: 'dsp_addsub_piped_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/coe_user/Documents/ECE574_Local/homework/hw3/assignment3.gen/sources_1/ip/dsp_addsub_piped_2/dsp_addsub_piped_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsp_addsub_piped_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/coe_user/Documents/ECE574_Local/homework/hw3/assignment3.srcs/sources_1/ip/dsp_addsub_piped_2/dsp_addsub_piped_2.xci
# IP: The module: 'dsp_addsub_piped_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/coe_user/Documents/ECE574_Local/homework/hw3/assignment3.gen/sources_1/ip/dsp_addsub_piped_2/dsp_addsub_piped_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsp_addsub_piped_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
