# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/coe_user/Documents/ECE574_VLSI/homework/hw3/assignment3.srcs/sources_1/ip/mult_piped_6/mult_piped_6.xci
# IP: The module: 'mult_piped_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/coe_user/Documents/ECE574_VLSI/homework/hw3/assignment3.gen/sources_1/ip/mult_piped_6/mult_piped_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_piped_6'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/coe_user/Documents/ECE574_VLSI/homework/hw3/assignment3.srcs/sources_1/ip/mult_piped_6/mult_piped_6.xci
# IP: The module: 'mult_piped_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/coe_user/Documents/ECE574_VLSI/homework/hw3/assignment3.gen/sources_1/ip/mult_piped_6/mult_piped_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_piped_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
