# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/coe_user/Documents/ECE574_Local/homework/final/FinalProject.srcs/sources_1/ip/blk_mem_data/blk_mem_data.xci
# IP: The module: 'blk_mem_data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/coe_user/Documents/ECE574_Local/homework/final/FinalProject.gen/sources_1/ip/blk_mem_data/blk_mem_data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_data'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/coe_user/Documents/ECE574_Local/homework/final/FinalProject.srcs/sources_1/ip/blk_mem_data/blk_mem_data.xci
# IP: The module: 'blk_mem_data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/coe_user/Documents/ECE574_Local/homework/final/FinalProject.gen/sources_1/ip/blk_mem_data/blk_mem_data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_data'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
